### ISSUE TITLE
open issue with reproduction step on GPU.js

### ISSUE THREAD

**Issue by robertleeplummerjr** [RobinKa/maxwell-simulation#10]
I saw this and would like to ensure you don't have to double up on kernels: https://github.com/RobinKa/maxwell-simulation/blob/9970b17a508afbdb28c372733f085e36e2b74b9b/src/kernels/rendering.ts#L62

Open an issue on GPU.js and we'll get it fixed.

**Comment by RobinKa** [comment]
Opened it here https://github.com/gpujs/gpu.js/issues/529
