### ISSUE TITLE
Support unsigned integer kernels

### ISSUE THREAD

**Issue by RobinKa** [RobinKa/maxwell-simulation#3]
Right now we are falling back to CPU when single-precision textures are not supported which is very slow.

**Comment by robertleeplummerjr** [comment]
Is this a problem with GPU.js?

**Comment by RobinKa** [comment]
Some devices like iPad 6 and other older ones don't support float textures. When I set the kernel precision to `unsigned` (or when I don't specify it at all) it would give a runtime error on those devices. I will try it again to get the exact error.

**Comment by RobinKa** [comment]
```
Error: Unhandled argument combination of NumberTexture and NumberTexture for argument named "magFieldX" on line 2, position 1:
 getAt(magFieldX, gx, gy, x, y) 2 function-node.js:1058
    astErrorOutput function-node.js:1058
    astCallExpression function-node.js:1625
    astGeneric function-node.js:1027
    astBinaryExpression function-node.js:313
    astGeneric function-node.js:964
    astReturnStatement function-node.js:155
    astGeneric function-node.js:958
    astFunction function-node.js:101
    astFunctionExpression function-node.js:1111
    astGeneric function-node.js:955
    toString function-node.js:376
    getPrototypes function-builder.js:330
    getPrototypeString function-builder.js:319
    translateSource kernel.js:248
    build kernel.js:554
    run kernel-run-shortcut.js:12
    shortcut kernel-run-shortcut.js:46
    stepMagnetic simulator.ts:192
    simStep App.tsx:261
```

In the past I encountered the same error when calling one function twice with differently typed parameters, but I haven't been able to figure out yet why this happens here.

**Comment by RobinKa** [comment]
Removing `getAt` everywhere and inlining it makes it not crash. On desktop and my phone (Nexus 6) this works, but on iPad 6 there is some issue with both Safari and Chrome (the entire screen turns blue, I assume some indexing or accuracy issue somewhere). Using WebGL1 for all of these.

**Comment by RobinKa** [comment]
Using regl now instead with half-float textures that work on most devices.
